# Generated by Django 4.0.2 on 2022-02-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100, verbose_name='Название песни')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('photo', models.FileField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('photo', models.FileField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, verbose_name='Название песни')),
                ('text', models.TextField(verbose_name='Текст Песни')),
                ('year', models.DateField(verbose_name='Дата выхода')),
                ('mp3', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miyagi_app.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('from_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miyagi_app.song', verbose_name='Из песни')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miyagi_app.song', verbose_name='Песня'),
        ),
    ]
